plugins {
    id 'com.android.application'
}

android {
    namespace 'com.wuwa.config.manager'
    compileSdk 36

    defaultConfig {
        applicationId 'com.wuwa.config.manager'
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName '1.0'
        buildConfigField 'int', 'PRESET_REVISION', '1'

        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    buildTypes {
        debug {
            buildConfigField 'boolean', 'ENABLE_DEBUG_LOGS', 'true'
        }
        release {
            debuggable false
            jniDebuggable false
            buildConfigField 'boolean', 'ENABLE_DEBUG_LOGS', 'false'
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        buildConfig true
    }

    packaging {
        resources.excludes += '/META-INF/{AL2.0,LGPL2.1}'
    }

    lint {
        abortOnError true
        checkReleaseBuilds true
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.14.0'
    implementation 'dev.rikka.shizuku:api:13.1.5'
    implementation 'dev.rikka.shizuku:provider:13.1.5'
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.5'

    testImplementation 'junit:junit:4.13.2'
}
